<a href="https://colab.research.google.com/github/tinachelwanii/CSS-My-Site/blob/main/nasscom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
{
  var1 = readline("Enter 1st number:")
  var2 = readline("Enter 2nd number:")
  var3 = readline("Enter 3rd number:")
  var4 = readline("Enter 4th number:")
}
var1=as.integer(var1)
print(var1)
var2=as.integer(var2)
print(var2)
var3=as.integer(var3)
print(var3)
var4=as.integer(var4)
print(var4)
print("The sum is: ",var1+var2+var3+var4)
cat("The sum is:",var1+var2+var3+var4,"End")

Enter 1st number:1
Enter 2nd number:2
Enter 3rd number:3
Enter 4th number:4
[1] 1
[1] 2
[1] 3
[1] 4
[1] "The sum is: "
The sum is: 10 End

In [ ]:
d = scan(what= double())
s = scan(what = " ")
c = scan(what = character())
print(d) #double
print(s)
print(c)

numeric(0)
character(0)
character(0)


In [ ]:
x <- 42
z=55
45 -> y
print(x+y+z)

[1] 142


In [ ]:
x <- "R Programming"
print(paste(x," is best function inside print()"))
print(paste0(x," is best(the paste0 function inside print())"))


[1] "R Programming  is best function inside print()"
[1] "R Programming is best(the paste0 function inside print())"


In [ ]:
x = "R Programming"
x1 = 255
x2 = 23.14
sprintf("is the best %s satistical language",x)
sprintf("%d is integer",x1)
sprintf("%f is float",x2)

[1] "is the best R Programming satistical language"

[1] "255 is integer"

[1] "23.140000 is float"

In [ ]:
x = "R Programming"
message("The best satistical language:", x)
message("This is R language")

The best satistical language:R Programming

This is R language



In [ ]:
x = "R Programming"
write.table(x,file="tina.txt")
write.table("the best statistical language", file = "my_data2.txt")

In [ ]:
x <- 155/7
print(x,digits = 2)
print(x,digits = 3)
print(x,digits = 4)
print(x,digits = 5)
print(x)



[1] 22
[1] 22.1
[1] 22.14
[1] 22.143
[1] 22.14286


In [ ]:
x <- matrix(c(2,NA,5,NA,8,NA,22,67,43),
     nrow = 3,byrow = TRUE)

     print(x)
     print(x, na.print= "BAD")

     [,1] [,2] [,3]
[1,]    2   NA    5
[2,]   NA    8   NA
[3,]   22   67   43
     [,1] [,2] [,3]
[1,]    2  BAD    5
[2,]  BAD    8  BAD
[3,]   22   67   43


In [ ]:
x <- 6
class(x)

[1] "numeric"

In [ ]:
s <- "R Pro"
class(s)

[1] "character"

In [ ]:
x <- c(76,72,56,100,63)
class(x)

[1] "numeric"

In [ ]:
x <- c(76,72,56,100.25,63.99,"Data Science")
x

[1] "76"           "72"           "56"           "100.25"       "63.99"       
[6] "Data Science"

In [ ]:
v <- TRUE
print(class(v))
print(v)

[1] "logical"
[1] TRUE


In [ ]:
v <- 2022L
print(class(v))

[1] "integer"


In [ ]:
v <- "TRUE"
print(class(v))

[1] "character"


In [ ]:
v <- charToRaw("Hello")
print(class(v))
v

[1] "raw"


[1] 48 65 6c 6c 6f

In [ ]:
apple <- c("red","green","yellow")
print(apple)

print(class(apple))

[1] "red"    "green"  "yellow"
[1] "character"


In [ ]:
list1 <- list(c(2,5,3),21.3,sin)
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")



In [ ]:
M = matrix( c('a','a','b','c','b','a'),nrow = 3,ncol=2,byrow = FALSE)
print(M)

     [,1] [,2]
[1,] "a"  "c" 
[2,] "a"  "b" 
[3,] "b"  "a" 


In [ ]:
a <- array(c('green','yellow'),dim=c(4,4))
print(a)

     [,1]     [,2]     [,3]     [,4]    
[1,] "green"  "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow" "yellow"
[3,] "green"  "green"  "green"  "green" 
[4,] "yellow" "yellow" "yellow" "yellow"


In [ ]:
apple_colors=c('green','green','yellow','red','red','red','green')
factor_apple=factor(apple_colors)
print(factor_apple)
print(nlevels(factor_apple))

[1] green  green  yellow red    red    red    green 
Levels: green red yellow
[1] 3


In [ ]:
BMI <- data.frame(
  gender = c("Male","Male","Female"),
  height = c(152,171.5,165),
  weight = c(81,93,78),
  Age = c(42,38,26)
)
print(BMI)


  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


In [ ]:
input_read2 <- readline()
input_read2 <- strsplit(input_read2,"e")
input_read2

welcome to nasscom session


[[1]]
[1] "w"             "lcom"          " to nasscom s" "ssion"

In [ ]:
input_read2 <- readline()
input_read2 <- strsplit(input_read2,"e")
input_read2

In [ ]:
input_read <- as.integer(readline())
input_read+1


2023


[1] 2024

In [ ]:
weight <- as.numeric(readline())
weight+1.5


30


[1] 31.5

In [ ]:
pi

[1] 3.141593

In [ ]:
10**2

[1] 100

In [ ]:
r=5
area_of_circle=pi*(r**2)
print(area_of_circle)


[1] 78.53982


In [ ]:
print(pi)
print(month.name)
print(letters)
print(LETTERS)
print(month.abb)

[1] 3.141593
 [1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December" 
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"
 [1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"


In [ ]:
5+5
5-5
5*5
5**3
35/10
5*3
5%%2
35%/%10


[1] 10

[1] 0

[1] 25

[1] 125

[1] 3.5

[1] 15

[1] 1

[1] 3

In [ ]:
#relational operator
5>=2

In [ ]:
Sys.Date()
Sys.time()

[1] "2024-02-07"

[1] "2024-02-07 06:50:57 UTC"

In [ ]:
Sys.setenv(TZ = "Asia/Kolkata")

current_time_ist <- Sys.time()

print(current_time_ist)


[1] "2024-02-07 12:25:28 IST"


In [ ]:
nchar("R language")

[1] 10

In [ ]:
sqrt(3)

[1] 1.732051

In [ ]:
log(5)
log(5, base =3)
log10(5)
log2(5)

[1] 1.609438

[1] 1.464974

[1] 0.69897

[1] 2.321928

In [ ]:
dir()

[1] "sample_data"

In [ ]:
ls()
objects()

[1] "area_of_circle"   "current_time_ist" "input_read"       "pb.date"         
[5] "r"                "weight"

[1] "area_of_circle"   "current_time_ist" "input_read"       "pb.date"         
[5] "r"                "weight"

In [ ]:
a <- c(2,3,4)
b <- c(10,20,10)
a+b
a*b
a/b
a^2

[1] 12 23 14

[1] 20 60 40

[1] 0.20 0.15 0.40

[1]  4  9 16

In [ ]:
help(sqrt)


In [ ]:
x=c(0:10,50)
x

[1]  0  1  2  3  4  5  6  7  8  9 10 50

In [ ]:
example(mean)


mean> x <- c(0:10, 50)

mean> xm <- mean(x)

mean> c(xm, mean(x, trim = 0.10))
[1] 8.75 5.50


In [ ]:
getwd()

data <- read.table("data.txt",
					header = FALSE, sep = " ")

print(data)

print(class(data))


[1] "/content"

   V1 V2 V3 V4 V5
1 100 NA  A NA  a
2 200 NA  B NA  b
3 300 NA  C NA  c
4 400 NA  D NA  d
5 500 NA  E NA  e
6 600 NA  F NA  f
[1] "data.frame"


In [ ]:
install.packages("xlsx")
getwd()
data <- read.xlsx("Book1.xlsx",
                   sheetIndex = 1,
                   header = FALSE)
print(data)
print(class(data))

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘rJava’, ‘xlsxjars’


Warning message in install.packages("xlsx"):
“installation of package ‘rJava’ had non-zero exit status”
Warning message in install.packages("xlsx"):
“installation of package ‘xlsxjars’ had non-zero exit status”
Warning message in install.packages("xlsx"):
“installation of package ‘xlsx’ had non-zero exit status”


[1] "/content"

ERROR: Error in read.xlsx("Book1.xlsx", sheetIndex = 1, header = FALSE): could not find function "read.xlsx"


In [ ]:
a=2:10
a <- c(1,2,5,8)
a
b <- seq(from=2, to=10 , by=2)
b
c<-seq(from=2, to=10,by=2)
b
c <- seq(1,10,3)
c
d <- seq(from=5,length=20,by=0.2)
d
d <- seq(2,22, length.out = 7)

[1] 1 2 5 8

[1]  2  4  6  8 10

[1]  2  4  6  8 10

[1]  1  4  7 10

[1] 5.0 5.2 5.4 5.6 5.8 6.0 6.2 6.4 6.6 6.8 7.0 7.2 7.4 7.6 7.8 8.0 8.2 8.4 8.6
[20] 8.8

In [ ]:
r=rep(3,10)
print(r)

 [1] 3 3 3 3 3 3 3 3 3 3


In [ ]:
country<- c("India"=100,"Pakistan"=50,"China"=125)
country

India Pakistan    China 
     100       50      125

In [ ]:
#G5_unit1_topicname

In [ ]:
country ["India"]

India 
  100

In [ ]:
population <- c(100,50,125)
country <- c("India","Pakistan","China")
names(population) <- country
population

India Pakistan    China 
     100       50      125

In [ ]:
k=c(5,4,6,7)
d <- (k<=4)
d

[1] FALSE  TRUE FALSE FALSE

In [ ]:
a <- c(2,3,4)
b <- c(10,20,10)
a+b
a*b
a/b
a^2

[1] 12 23 14

[1] 20 60 40

[1] 0.20 0.15 0.40

[1]  4  9 16

In [ ]:
x <- 25.2578912345
format(round(x,2),nsmall=2)

[1] "25.26"

In [ ]:
cat("Everyone","is","a","programmer")
paste("Everyone","is","a","coder")
cat("everyone","is","a","programmer",sep="*")

Everyone is a programmer

[1] "Everyone is a coder"

everyone*is*a*programmer

In [ ]:
x <- c(10,20,30,45,78)
x[1]
x[2:4]

[1] 10

[1] 20 30 45